# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(607, 571)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_pathIn = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_pathIn.setObjectName("lineEdit_pathIn")
        self.horizontalLayout.addWidget(self.lineEdit_pathIn)
        self.pushButton_fileDialogIn = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_fileDialogIn.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_fileDialogIn.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_fileDialogIn.setObjectName("pushButton_fileDialogIn")
        self.horizontalLayout.addWidget(self.pushButton_fileDialogIn)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_password = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_password)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_pathOut = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_pathOut.setObjectName("lineEdit_pathOut")
        self.horizontalLayout_3.addWidget(self.lineEdit_pathOut)
        self.pushButton_fileDialogOut = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_fileDialogOut.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_fileDialogOut.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_fileDialogOut.setObjectName("pushButton_fileDialogOut")
        self.horizontalLayout_3.addWidget(self.pushButton_fileDialogOut)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.formLayout)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setStyleSheet("QTextEdit {\n"
"    font: 9pt \"Noto Sans\";\n"
"}")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_hideMessage = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_hideMessage.setObjectName("pushButton_hideMessage")
        self.horizontalLayout_2.addWidget(self.pushButton_hideMessage)
        self.pushButton_getMessage = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_getMessage.setObjectName("pushButton_getMessage")
        self.horizontalLayout_2.addWidget(self.pushButton_getMessage)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 607, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Путь к исходному стегоконтейнеру:"))
        self.pushButton_fileDialogIn.setText(_translate("MainWindow", "..."))
        self.label_2.setText(_translate("MainWindow", "Пароль:"))
        self.label_4.setText(_translate("MainWindow", "Путь к конечному стегоконтейнеру:"))
        self.pushButton_fileDialogOut.setText(_translate("MainWindow", "..."))
        self.label_3.setText(_translate("MainWindow", "Скрываемое сообщение:"))
        self.pushButton_hideMessage.setText(_translate("MainWindow", "Скрыть сообщение"))
        self.pushButton_getMessage.setText(_translate("MainWindow", "Получить сообщение"))
